# Generated by Django 5.1.7 on 2025-04-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_event_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalobject',
            name='Name',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
