# Generated by Django 5.1.7 on 2025-05-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_globalobject_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('GlobalObject', 'DayID')},
        ),
    ]
