# Generated by Django 5.1.7 on 2025-05-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_alter_day_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.globalobject'),
        ),
    ]
