# Generated by Django 5.1.7 on 2025-05-11 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_event_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('shift_id', models.CharField(max_length=10)),
                ('requirement', models.PositiveIntegerField(default=0)),
                ('weight_under', models.PositiveIntegerField(default=100)),
                ('weight_over', models.PositiveIntegerField(default=1)),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='calendarapp.globalobject')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='ShiftOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.CharField(choices=[('ON', 'On'), ('OFF', 'Off')], max_length=3)),
                ('weight', models.FloatField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.day')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.globalobject')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.shifttype')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_type', models.CharField(choices=[('ON', 'Shift On'), ('OFF', 'Shift Off')], max_length=4)),
                ('weight', models.FloatField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1)),
                ('from_file', models.BooleanField(default=False, help_text='True dacă cererea a fost validă (apărută) în fișierul original')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='calendarapp.day')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='calendarapp.globalobject')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to=settings.AUTH_USER_MODEL)),
                ('shift_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='calendarapp.shifttype')),
            ],
            options={
                'verbose_name': 'Shift Request',
                'verbose_name_plural': 'Shift Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DayOffOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.day')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.globalobject')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nurse', 'day')},
            },
        ),
        migrations.CreateModel(
            name='DayOffRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1)),
                ('from_file', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.day')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.globalobject')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nurse', 'day')},
            },
        ),
    ]
