# Generated by Django 5.1.7 on 2025-05-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_coveragerequirement_shiftoption_shiftrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoffoption',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.nurse'),
        ),
        migrations.AlterField(
            model_name='dayoffrequest',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.nurse'),
        ),
    ]
