# Generated by Django 5.1.7 on 2025-05-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_alter_dayoffoption_nurse_alter_dayoffrequest_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftoption',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.nurse'),
        ),
    ]
