# Generated by Django 5.1.7 on 2025-05-11 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0011_alter_shiftoption_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftrequest',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='calendarapp.nurse'),
        ),
    ]
