# Generated by Django 5.1.7 on 2025-05-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0013_globalobject_totalminutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalobject',
            name='TotalMinutesToMax',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalobject',
            name='TotalMinutesToMin',
            field=models.IntegerField(default=0),
        ),
    ]
