# Generated by Django 5.1.7 on 2025-05-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0014_globalobject_totalminutestomax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='TotalMins',
            field=models.IntegerField(default=0),
        ),
    ]
