# Generated by Django 5.1.7 on 2025-05-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0015_nurse_totalmins'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayshifttype',
            name='ActualyNrCovered',
            field=models.IntegerField(default=0),
        ),
    ]
