# Generated by Django 5.1.7 on 2025-05-28 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0016_dayshifttype_actualynrcovered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleGenerationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('events_json', models.JSONField(help_text='Lista evenimentelor (title, start, end, description)')),
                ('kpi_hard', models.FloatField(blank=True, null=True)),
                ('kpi_soft', models.FloatField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.globalobject', verbose_name='Unitate medicală')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizator')),
            ],
            options={
                'verbose_name': 'Log generare orar',
                'verbose_name_plural': 'Istoric generări orar',
                'ordering': ['-generated_at'],
            },
        ),
    ]
