# Generated by Django 5.1.7 on 2025-06-02 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0017_schedulegenerationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call_nurses', models.ManyToManyField(blank=True, related_name='to_be_called', to='calendarapp.nurse')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('remove_nurses', models.ManyToManyField(blank=True, related_name='to_be_removed', to='calendarapp.nurse')),
            ],
        ),
    ]
