# Generated by Django 4.2.16 on 2025-06-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0018_emergencyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='nurse',
            field=models.ForeignKey(default='A0', on_delete=django.db.models.deletion.CASCADE, to='calendarapp.nurse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='shiftType',
            field=models.ForeignKey(default='A0', on_delete=django.db.models.deletion.CASCADE, to='calendarapp.shifttype'),
            preserve_default=False,
        ),
    ]
