# Generated by Django 4.2.16 on 2025-06-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0019_event_day_event_nurse_event_shifttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Denied')], default='P', max_length=1),
        ),
    ]
