# Generated by Django 4.2.16 on 2025-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0020_emergencyrequest_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nursedayshifttype',
            unique_together={('Nurse', 'Day', 'ShiftType')},
        ),
        migrations.AddIndex(
            model_name='nursedayshifttype',
            index=models.Index(fields=['Nurse', 'Day', 'ShiftType'], name='idx_nurse_day_shift'),
        ),
    ]
