# Generated by Django 4.2.16 on 2025-06-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0021_alter_nursedayshifttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nurseday',
            options={'verbose_name': 'NurseDay', 'verbose_name_plural': 'NurseDays'},
        ),
        migrations.AlterUniqueTogether(
            name='nurseday',
            unique_together={('Nurse', 'Day')},
        ),
        migrations.AddIndex(
            model_name='nurseday',
            index=models.Index(fields=['Nurse', 'Day'], name='idx_nurse_day'),
        ),
    ]
