# Generated by Django 4.2.16 on 2025-06-05 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0022_alter_nurseday_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='nurse',
        ),
        migrations.RemoveField(
            model_name='event',
            name='shiftType',
        ),
        migrations.AddField(
            model_name='event',
            name='NurseDayShiftType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.nursedayshifttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='calendarapp.globalobject'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
