# Generated by Django 5.1.6 on 2025-03-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_meetingtime_remove_instructor_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HorizonLength', models.IntegerField(default=0)),
                ('TotalKPIHard', models.FloatField(default=0.0)),
                ('KPIHardOneShiftOneDay', models.FloatField(default=0.0)),
                ('KPIHardShiftRotation', models.FloatField(default=0.0)),
                ('KPIHardMaxNrOfShifts', models.FloatField(default=0.0)),
                ('KPIHardMaxTotalMinutes', models.FloatField(default=0.0)),
                ('KPIHardMinTotalMinutes', models.FloatField(default=0.0)),
                ('KPIHardMaxConsShifts', models.FloatField(default=0.0)),
                ('KPIHardMinConsShifts', models.FloatField(default=0.0)),
                ('KPIHardMinConsDaysOff', models.FloatField(default=0.0)),
                ('KPIHardMaxNrWeekend', models.FloatField(default=0.0)),
                ('KPIHardDaysOff', models.FloatField(default=0.0)),
                ('KPISoftShiftOnRequest', models.FloatField(default=0.0)),
                ('KPISoftShiftOffRequest', models.FloatField(default=0.0)),
                ('KPISoftUnderCover', models.FloatField(default=0.0)),
                ('KPISoftOverCover', models.FloatField(default=0.0)),
                ('KPITotalKPISoft', models.FloatField(default=0.0)),
            ],
        ),
    ]
