# Generated by Django 5.1.6 on 2025-03-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_globalobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('EmployeeID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('MaxShifts', models.CharField(max_length=400)),
                ('MaxTotalMins', models.IntegerField()),
                ('MinTotalMins', models.IntegerField()),
                ('MaxConsShifts', models.IntegerField()),
                ('MinConsShifts', models.IntegerField()),
                ('MinConsDaysOff', models.IntegerField()),
                ('MaxWeekends', models.IntegerField()),
                ('DaysOff', models.FloatField()),
                ('GlobalObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.globalobject')),
            ],
        ),
    ]
