# Generated by Django 5.1.6 on 2025-03-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_nurse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('DayID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('GlobalObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='app.globalobject')),
            ],
        ),
        migrations.CreateModel(
            name='NurseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsDayOff', models.BooleanField()),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.day')),
                ('Nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurse')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('ShiftID', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('LengthInMins', models.FloatField()),
                ('ForbiddenShifts', models.JSONField()),
                ('GlobalObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.globalobject')),
            ],
        ),
        migrations.CreateModel(
            name='NurseShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaxShifts', models.IntegerField()),
                ('Nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurse')),
                ('ShiftType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shifttype')),
            ],
        ),
        migrations.CreateModel(
            name='NurseDayShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsAssigned', models.BooleanField()),
                ('IsOnRequest', models.BooleanField()),
                ('IsOffRequest', models.BooleanField()),
                ('OnRequestWeight', models.FloatField()),
                ('OffRequestWeight', models.FloatField()),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.day')),
                ('Nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurse')),
                ('NurseDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nurseday')),
                ('ShiftType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shifttype')),
            ],
        ),
        migrations.CreateModel(
            name='DayShiftType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NrRequired', models.IntegerField()),
                ('OverCoverWeight', models.IntegerField()),
                ('UnderCoverWeight', models.IntegerField()),
                ('Day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.day')),
                ('ShiftType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shifttype')),
            ],
        ),
    ]
