# Generated by Django 5.1.7 on 2025-05-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unitate_medicala',
            field=models.PositiveIntegerField(default=0, help_text='ID-ul unității medicale asociate', verbose_name='Unitate medicală'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=' ', help_text='Un nume de utilizator', max_length=150, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
